version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /usr/src/app/node_modules
      - C:\Users\dy-ko\Desktop\dockerfile-folder\react-app:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true